### ISSUE TITLE
Enable/Disable yaml validation for specific yaml schema

### ISSUE THREAD

**Issue by danak95** [redhat-developer/vscode-yaml#649] opened 2021-11-23 14:02 UTC
Hey,

I'll be glad to have the option to enable/disable the yaml validation for a specific schema.
Right now I can define yaml schemas by writing those lines in settings.json
`"yaml.schemas": {
        "blabla.schema.json": ["*.bla"],
        "blabla2.schema.json": ["*.bla2"]
}`
And I can disable/enable yaml validation by writing those lines
`"yaml.validation": true/false`

But that approach would validate/not validate all of the schemas written above. I want to be able to enable one of the schemas, and disable the other.

**Comment by frank0r** [comment] 2021-12-15 19:43
+1

**Comment by gorkem** [comment] 2022-03-16 03:24
What exactly is this trying to achieve? Disable validation for certain schemas but still use the schema for code-assist? OR do we just need a way to keep the list of schemas on the settings and still have schema optionally enabled/disabled? If it is the latter I do not think validation is the correct word to describe it.

**Comment by msivasubramaniaan** [comment] 2022-03-16 05:48
I hope the user expects to have list of schemas on the settings and keep some schema optionally enabled/disabled. In that case shall we use "enable": false and by default it will be true.

**Comment by gorkem** [comment] 2022-03-18 12:57
If this is for keeping a list of schema mappings. I would rather not have this built-in and maintained as part of this extension and the `yaml-language-server`. I imagine you can keep a list of mappings on a  plain file and copy and paste them as efficiently as flipping enable/disable. 
Closing as wontfix.

**Closed by gorkem** 2022-03-18 12:57 UTC

**Comment by davestephens** [comment] 2022-09-11 16:00
To give a more specific use case where this would be helpful;

I'm writing Molecule tests for my Ansible roles (my playbook has >1 role), and Molecule has a concept of abstracting out repeated config to a "base" config. My base config validates fine, but each of the individual role Molecule config files is firing a problem as the schema doesn't validate on the role configs, due to missing most of the keys (by design). 

This breaks validation (but is a valid Molecule config file): https://github.com/davestephens/ansible-nas/blob/master/roles/hello_world/molecule/default/molecule.yml

So, I'd like to be able to switch off the Molecule schema validation checking, but not ALL of the YAML schema validation on my project. Happy to elaborate further if it's of use.

**Comment by Relequestual** [comment] 2025-03-14 14:20
Given support for OpenAPI 3.0 is [broken](https://github.com/redhat-developer/yaml-language-server/pull/1006#issuecomment-2719049352), it would be nice if you could disable validation for a specific file, but key using the language server for other YAML files.

This way you can enable other validation tools to work with OADs.
