### ISSUE TITLE
Add support for a keyword '$schema' to yaml files

### ISSUE THREAD

**Issue by jsbroks** [redhat-developer/vscode-yaml#314] opened 2020-07-11 13:16 UTC
Similar to how you can currently use $schema in JSON, it would be nice to add this support instead of having to go into vscode settings.

**Comment by JPinkney** [comment] 2020-07-11 13:59
Duplicate of https://github.com/redhat-developer/vscode-yaml/issues/151

**Closed by JPinkney** 2020-07-11 13:59 UTC
