### ISSUE TITLE
.yml files are ignored

### ISSUE THREAD

**Issue by giovannicandido** [redhat-developer/vscode-yaml#87] opened 2018-05-25 13:10 UTC
Using it with ansible, all .yml files has no syntax highlight
Renaming file to .yaml enables but is not compeling to rename all my files.

**Comment by giovannicandido** [comment] 2018-05-30 11:01
Is not a kubernetes file.

![problem](https://mfirkw.bn.files.1drv.com/y4mmMu2o9t8RGOhma8tiaPnPbhaS4oy4OGUxL9U1I6rFa9tvW8ZgBVtBCzvV_-7yC2q944b65mGMn9TzKX3a6dPAmHfi5psF3lsSPJBlVTW530ZUGoOdaYcRuvfe12UjjYiyMr0h4CBxngl-9zj-3ufo0ztYF1cKBTijXekb-eC3GhJpv2e6xTYIEeUkttglIfmhLYWWXgDm2pyzmFHQfzAHmyqyGKnsmFLXCg2mY4z9jg/vscode.png)

**Comment by giovannicandido** [comment] 2018-05-31 11:19
I test in Windows and is ok. Problem is on Ubuntu Linux.

**Comment by giovannicandido** [comment] 2018-05-31 12:01
The highlight is not working on folders:
 **roles**
 **playbooks**

This video show the behaviour: https://1drv.ms/v/s!AoHvV-Rb6N9QgoJ4ulk8Z7RUq2kCUg

**Comment by JPinkney** [comment] 2018-05-31 13:27
Ah, thats such weird behaviour. I'll look into it and fix it for the next release.

**Comment by timm088** [comment] 2018-06-11 08:02
Hrmm, not sure if related, but in my case, when using the 'comment' shortcut in .yaml files, i now get `/* my thing */` 

New behaviour, does not occur in .yml files

**Comment by JPinkney** [comment] 2018-10-01 23:29
Upon examination again I think that this isn't vscode-yaml, it looks like for some reason the .yml file is not getting registered as the yaml file type when opened. Though I'm not entirely why it isn't registering _shrugs_

**Comment by nomoresecrets** [comment] 2019-06-20 13:51
had the same issue with *.yml files not being recognized as "Yaml" filetype, Check your settings (user, directory and workspace) for "files.associations" settings.

**Comment by JPinkney** [comment] 2019-06-20 13:56
@nomoresecrets In your case did one of your plugins associate yml files with some other type? It looks like the vscode-ansible extension for example associates *.yml files with ansible (https://github.com/VSChina/vscode-ansible#usage) and i'm guessing that overrides the default association with yaml

**Comment by nomoresecrets** [comment] 2019-06-20 14:16
yeah, I had manually set the association to "ansible" in all three settings files which drove me crazy b/c I didn't know you can have three different files^^

**Comment by Morriz** [comment] 2020-01-29 13:27
Can we please get a fix for this simple problem?

**Comment by JPinkney** [comment] 2020-04-03 22:34
Re-examining the problem, it looks like the filetype wasn't set to YAML it was set to plaintext (you can see it in the bottom right of the video when you open up one of the files that weren't highlighted) and that was the cause of this issue.

Both .yml and .yaml files should automatically associate to the YAML filetype and if they aren't it ends up as an issue with vscode itself, not with this extension so I'm going to close this.

**Closed by JPinkney** 2020-04-03 22:34 UTC
