### ISSUE TITLE
Warn about vscode-ansible conflict

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-yaml#404] opened 2020-12-01 21:48 UTC
### Is your enhancement related to a problem? Please describe.
When vscode-ansible and vscode-yaml are both installed, because vscode-ansible ships the yaml server users see duplicate yaml syntax errors.

### Describe the solution you would like

What I suggest is that the vscode-yaml extension detects when the ansible extension is installed (vscode.extensions.getExtension(‘vscoss.vscode-ansible’)) and then it informs the user about the problem and provides the option to uninstall the ansible extension (this can be implemented using the VS Code CLI).

**Comment by joshuawilson** [comment] 2020-12-01 22:00
Is there a way to check for the second installed instance and where it is? I'm asking because what happens if it is in another extension?
Just wandering if we can make the warning generic.

**Comment by JPinkney** [comment] 2020-12-01 22:38
It might be possible to make it a tad more generic. I did a quick look and you can do something like:
```
extensions.all.forEach((extension) => {
    if (extension.packageJSON.dependencies.hasOwnProperty("yaml-language-server")) {
        // show warning
   }
});
```

This check would only work though if everyone who had that dependency was spawning the language server and not just using the package as a library. If they were using the package as a library there would be false positives so I'm not sure if it would be worth it

**Comment by joshuawilson** [comment] 2020-12-01 22:44
A false positive is worse. Maybe just do the hard coded fix for this singular issue.

We can always come back to it if there is another case found.

**Comment by gorkem** [comment] 2020-12-02 01:08
we can't depend on the "dependencies".

**Comment by fbricon** [comment] 2020-12-02 08:27
Yup, better take the conservative approach and rely on vscode.extensions.getExtension(‘vscoss.vscode-ansible’) for now to avoid false positives. If conflicts with other extensions are reported, it'll be easy to update and release a fix.

If you really really really want to be more "flexible", i.e. don't want to rerelease a new update every time you flag a conflicting dependency, you can always have vscode-yaml fetch a list of offending extensions at startup, so it's stays up-to-date even after a release. But that might be a tad overkill for now.

**Comment by egamma** [comment] 2020-12-02 14:47
The ansible extension provides a setting `ansible.validate` https://github.com/VSChina/vscode-ansible/blob/2201b217b4344b46adec31f3eed38e256a7528b6/package.json#L203 that supports to disable validation. Since you are already adding some special code for the ansible extension you could also programmatically disable this setting using the VS Code configuration setting API and disable validation.

**Comment by joshuawilson** [comment] 2020-12-02 15:43
Thanks @egamma that would be nicer then asking the user to uninstall the ansible extension. I think we should still tell them the issue and then give them the option to turn it off with a button press. Since the issue is that we are seeing double errors, that is not critical and they may want the current yaml validation in anisble.

That way they know the cause and can make it go away if they choose to.

**Comment by egamma** [comment] 2020-12-02 20:31
Quick update to avoid a wasted effort, after further discussion with the team that owns this extension it was decided to deprecate and retire the ansible extension. Having an extension that is not actively maintained will cause more frustration for users in the future. This was also suggested by users https://github.com/VSChina/vscode-ansible/issues/272.

**Comment by kohtala** [comment] 2021-05-12 07:08
I see commit eb107edee6973be7a7d0909025e87019863f3142 added a notification _Ansible extension is incompatible with VSCode-YAML. Please uninstall it._ Thanks.

@JPinkney, maybe I am a bit illiterate, but I was afraid pressing the offered Uninstall button because I was not sure which extension would be uninstalled. Would it be possible to reword to something like "VSCode-YAML found incompatible extensions. Please uninstall Ansible."

**Comment by ssbarnea** [comment] 2022-04-04 14:42
Closing because the original posting is no longer true. Both ansible and yaml vscode ansible are developed by redhat and they team-up quite well.

Just be sure you are using the official Ansible extension from https://marketplace.visualstudio.com/items?itemName=redhat.ansible and not another one, especially as there were quite a few floating around over time.

**Closed by ssbarnea** 2022-04-04 14:42 UTC
Labels: enhancement
