### ISSUE TITLE
Local YAML schema applied to schema file itself

### ISSUE THREAD

**Issue by dmke** [redhat-developer/vscode-yaml#894] opened 2023-03-06 09:29 UTC
## Describe the bug

I've got the following files:

- `permission.schema.yml`

  ```yaml
  ---
  $id:      urn:x-intern
  $schema:  http://json-schema.org/draft/2020-12/schema

  type: object
  additionalProperties:
    type: object
    required: [name]
    additionalProperties: false
    properties:
      name:
        type: string
  ```

- `permission.yml`

  ```yaml
  ---
  foo:
    name: bar
  ```

- `.vscode/settings.json`

  ```yaml
  {
    "yaml.schemas": {
      "./permission.schema.yml": "permission.yml"
    }
  }
  ```

## Expected Behavior

The `permission.schema.yml` should not be applied to itself:

1. It has its own `$schema` property, pointing to the JSON schema draft 2020-12.
2. The configured glob pattern (`permission.yml`) does not match `permission.schema.yml`.

## Current Behavior

The local schema is applied to the local schema itself, resulting in a false problem detection:

![image](https://user-images.githubusercontent.com/327411/223068881-828e2bcb-f090-42ed-a3fd-1c1dfd6c6d00.png)

## Steps to Reproduce

1. Open VSCode in an existing or new workspace/folder.
2. Create the files `permission.yml`, `permission.schema.yml` and `.vscode/settings.json`.
3. Open the `permission.schema.yml` in the editor.
4. Observe the errors/problems.

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux (Debian 11, X11, Gnome)
- [ ] other (please specify)

Extension is `redhat.vscode-yaml` v1.11.0.

**Comment by odiak** [comment] 2023-04-21 05:12
I've got same problem,
and it doesn't happen if the schema file isn't referenced on `yaml.schemas` setting.

I roughly read source code of YAML language service, and maybe I found cause of the problem.

https://github.com/redhat-developer/yaml-language-server/blob/cf3f79202524ba979f1f4011636b85d08d81bdcb/src/languageservice/services/yamlSchemaService.ts#L408-L417

**Comment by DetachHead** [comment] 2023-06-15 08:54
duplicate of #477

**Comment by bluefeet** [comment] 2023-06-19 16:20
This seems very much related to a problem I just found - that the `$schema` field is completely ignored. I would think that if `$schema` is declared in the YAML file it would override any settings or automatic schema.

**Closed** 2023-06-22 16:38 UTC
Labels: bug
