### ISSUE TITLE
Custom tags not working

### ISSUE THREAD

**Issue by rvansa** [redhat-developer/vscode-yaml#137] opened 2018-11-16 20:22 UTC
I have trouble getting the custom tags working. This are my user settings:

`cat ~/.config/Code/User/settings.json`
```json
{
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "yaml.customTags": [ "!rampPerSec", "!constantPerSec"]
}
```
and this is the yaml that fails to be parsed:
```yaml
foo:
  - !constantPerSec bar: gee
```
VSCode version: 1.28.2
YAML Support by Red Hat version: 0.1.0
possibly conflicting plugin? Ansible 0.5.2 (extension association is to YAML, not ansible, though).

I'll be grateful for any hints. I've tried restarting VSCode couple of times, or placing the `yaml.customTags` to workspace settings instead but it did not help. Removing exclamation marks didn't help either. Thank you.

**Comment by rvansa** [comment] 2018-11-19 08:36
`!con` is underlined with `unknown tag <!constantPerSec>`
`: gee` is underlined with `bad indentation of sequence entry`

**Comment by JPinkney** [comment] 2018-11-19 14:09
I think in this case you would technically need to do:

"yaml.customTags": [
       "!constantParSec sequence"
 ]

However it looks like there are quite a few bugs in custom tags right now anyways so that won't work currently. I'm working on a fix

**Comment by rvansa** [comment] 2018-11-19 16:51
That gets me only halfway: With `!constantPerSec sequence` the `: gee` is underlined with
`unacceptable node kind for !<!constantPerSec> tag; it should be "sequence", not "scalar"`

When I try `!constantPerSec scalar`, it complains about indentation...

Do you plan to include 'any' type as well? Or will you make sure that the same tag can be applied to multiple types? Thanks.

**Comment by JPinkney** [comment] 2018-11-30 16:36
Currently, there are no plans to include (the code that has the issue doesn't live here it lives in http://github.com/mulesoft-labs/yaml-ast-parser/issues iirc). 

` Or will you make sure that the same tag can be applied to multiple types? Thanks.`

I hope to do this/someone adds this in the future, it would be very useful.

**Comment by AndyJPhillips** [comment] 2019-01-23 17:52
I'm was getting a similar problem (Cloudformation yaml tags were causing unknown tag errors), I managed to 'fix' it by:

- disabling all dependent VSCode extensions (Ansible etc) 
- disabling the YAML extension
- re-enable the YAML extension

For reference my versions are:

VSCode: 1.30.2
YAML extension: 0.2.1

Here's my yaml.customTags:

`"yaml.customTags": [
        "!And sequence",
        "!Equals sequence",
        "!If sequence",
        "!Not sequence",
        "!Or sequence",
        "!Base64",
        "!Cidr sequence",
        "!FindInMap sequence",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Join sequence",
        "!Select sequence",
        "!Split sequence",
        "!Sub",
        "!Ref"
    ]`

**Comment by AndyJPhillips** [comment] 2019-01-23 17:56
In more news - as soon as I re-enable the Ansible 0.5.2 extension and reload it breaks the yaml custom tags

**Comment by efim-a-efim** [comment] 2019-03-07 10:11
Same problem here. Looks like Ansible extension breaks YAML custom tags functionality.

**Comment by JPinkney** [comment] 2019-05-28 18:45
The ansible extension uses a fork of this one for some reason :man_shrugging: and because of that we can't actually stop it from showing the error see: https://github.com/redhat-developer/vscode-yaml/issues/178 but it looks like the actual issue was fixed so I'm going to close the issue

**Closed by JPinkney** 2019-05-28 18:45 UTC

**Comment by smiller171** [comment] 2019-05-28 20:00
I'm not able to get it working even after disabling the Ansible extension unfortunately.

**Comment by JPinkney** [comment] 2019-05-28 20:02
@smiller171 Can you open a new issue with your custom tags and also a picture whats in the text document (similar to what was posted in the issue) and other extensions installed.

**Comment by mil1i** [comment] 2019-12-20 18:14
I have also tried @AndyJPhillips method above and am not able to get custom tags to work after disabling all extensions and re-enabling just the YAML extension.

I have tried removing all custom tags and just trying one at a time. None are working. I am trying to get the Cloudformation (!Ref, !Sub, etc) custom tags to work.

I've tried with just !Ref, !Sub. I've tried !Sub scalar, !Sub sequence, !Sub mapping. Nothing.

![Screen Shot 2019-12-20 at 11 08 38 AM](https://user-images.githubusercontent.com/8459426/71280924-d309a280-2319-11ea-92af-40dac0a87e1f.png)

**Comment by abohne** [comment] 2019-12-23 16:17
I posted another workaround at https://github.com/VSChina/vscode-ansible/issues/230#issuecomment-561281378.

**Comment by ssbarnea** [comment] 2020-01-18 17:20
Or to rephrase this bug is caused by https://github.com/adamvoss/vscode-yaml/issues/16 extension which hijacks yaml customTagsconfig and overrides it for all YAML files, not only for Ansible ones, breaking a huge number of YAML tools.

**Comment by cweekly** [comment] 2021-12-03 22:35
FWIW, on MacOS 11.6.1, latest VSCode 1.62.3, extension v1.2.2, I was annoyed by supposed syntax errors in yml files (`.gitlab-ci.yml`, `cicd/*.yml`) containing lines like `!reference [.basic_no_merge_rules, rules]`.   

AFAICT, the GitLab Workflow extension still can't properly validate yml files with custom tags like "!reference", but thanks to the comments here, I could at least get rid of the syntax errors:
```
  "yaml.customTags": [
    "!reference sequence"
  ], 
```

**Comment by etaslicukur** [comment] 2024-10-03 16:43
I am currently experiencing this issue and I don't have Ansible extension installed/enabled.
