### ISSUE TITLE
yaml extension conflict with vs-kubernetes extension for snippet suggestions

### ISSUE THREAD

**Issue by hefayed** [redhat-developer/vscode-yaml#717] opened 2022-03-16 02:56 UTC
## Summary
when trying to create yaml files for kubernetes suggestions doesnt show up , looks like it conflict with vscode kubernetes extension , any suggestion how to isolate the issue ?

## Relevant information
see below the screenshot
<img width="756" alt="image" src="https://user-images.githubusercontent.com/13040034/158507343-a39ea08a-5431-4864-8c27-3d12f2d0fa3b.png">

**Comment by hefayed** [comment] 2022-03-16 03:01
my settings is as follow

{
    "yaml.schemas": {
        "kubernetes": "*.yaml"
    }
}

**Comment by hefayed** [comment] 2022-03-16 03:15
i have removed the kubernetes extension and now suggestion appear after i write the full word

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/13040034/158509700-c6e31c09-0c23-44e2-8770-790352fcc5c0.png">

**Comment by hefayed** [comment] 2022-03-16 04:16
another strange thing, if i add metadata suggestions appear

<img width="1832" alt="image" src="https://user-images.githubusercontent.com/13040034/158515741-4bd99dbb-118f-4343-addf-b476e188fdd1.png">

**Comment by gorkem** [comment] 2022-05-09 00:58
duplicate of #705

**Comment by gorkem** [comment] 2022-05-09 00:59
closing in favour of #705

**Closed by gorkem** 2022-05-09 00:59 UTC
Labels: bug, duplicate
