### ISSUE TITLE
Uses the wrong schema, even when yaml.schemas is set

### ISSUE THREAD

**Issue by Xunnamius** [redhat-developer/vscode-yaml#397] opened 2020-11-22 07:31 UTC
## Describe the bug

![wtfbbq](https://user-images.githubusercontent.com/656017/99897421-f8f0a300-2c5e-11eb-8771-8a50be406ec2.png)

I'm using this extension and the GitHub Actions YAML extension. The last three error messages (using the proper schema) are from that other extension. The erroneous errors above them are from this extension. Disabling the GitHub Actions extension makes those last three (correct, proper) errors disappear, leaving the false errors this extension is reporting. 

The problem: this extension thinks my GitHub Actions workflow file is a "deploy php" file and so uses the wrong schema... simply because it has the word "deploy" in its file name. Change the name to `build-test-deplox.yml` and everything works. I can't make this extension ignore YAML files and I can't force this extension to use the correct schema (on the right, you can see the `yaml.schemas` setting being completely ignored).

Unfortunately for my `.github/dependabot.yml` file, I've had to disable this extension for now. Am I doing something wrong here?

## Expected Behavior
Use https://json.schemastore.org/github-workflow for `build-test-deploy.yml` like I told it to

## Current Behavior
Uses https://raw.githubusercontent.com/deployphp/deployer/master/src/schema.json instead

## Steps to Reproduce
1. Have `.github/workflows/build-test-deploy.yml` file in your project
2. Observe this extension invoke the wrong schema
3. Try to override the schema for that file (using both full path and simple file name)
4. Observe this extension continue to invoke the wrong schema

Bonus: replace "https://json.schemastore.org/github-workflow" with "https://json.schemastore.org/github-workflowfdsfdsff"
in `yaml.schemas` and the extension recognizes that the schema does not exist, so *it is receiving the proper schema from `settings.json`*!

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)

**Comment by gorkem** [comment] 2020-11-22 07:57
Looks like it is related to https://github.com/redhat-developer/yaml-language-server/issues/250

**Comment by c00** [comment] 2020-12-02 03:18
I'm experiencing the same issue. Slightly related, initially the plugin keeps guessing the wrong schema to apply. But then overwriting its guess with a setting as described in this issue does not work.

**Comment by cfbao** [comment] 2020-12-03 15:53
Same issue with `build_and_deploy.yml`

> Looks like it is related to [redhat-developer/yaml-language-server#250](https://github.com/redhat-developer/yaml-language-server/issues/250)

Want to highlight (from linked issue) that disabling schema store can work around this issue.

**Comment by badsyntax** [comment] 2021-01-06 13:51
Having the same problem, with any github workflow file named '\*deploy\*'. I'm unable to set the schema with:

```json
"yaml.schemas": {
  "https://json.schemastore.org/github-workflow": "/.githhub/workflows/**/*.yml"
}
```

**Comment by JPinkney** [comment] 2021-01-06 14:01
It looks like `"/.githhub/workflows/**/*.yml"` is spelt wrong, it should probably be `"/.github/workflows/**/*.yml"`. This issue is going to be fixed in the next release

**Comment by badsyntax** [comment] 2021-01-06 14:04
@JPinkney good spot! Unfortunately it makes no difference, it's still using the `deployphp` schema.

**Comment by Sytten** [comment] 2021-02-10 19:54
FYI @JPinkney I still have issues for some templates

**Comment by libsamek** [comment] 2021-02-17 09:12
I'm having a similar issue with GitLab CI configuration file, which contains `deploy` in its name. I have tried adding gitlab schema into yaml.schemas, but it makes no difference.

**Comment by l3d00m** [comment] 2021-02-21 13:19
![image](https://user-images.githubusercontent.com/12055376/108626274-9b334900-744f-11eb-93d5-d42e0c08e084.png)

This still seems to be happening on YAML 0.15.0. VSCode about output

```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.15-1-MANJARO
```

**Comment by l3d00m** [comment] 2021-02-23 10:04
Interestingly enough, this issue only happens if the action is named `deploy.yml`. It works perfectly for `deploy-dev.yml` or my build actions.

**Comment by xsalazar** [comment] 2021-02-25 22:24
I just ran into this same issue, and it definitely seems related to not only having `deploy` in the file name, but also position (maybe relative to symbol-separators?).

#### dockery_deploy.yml
![image](https://user-images.githubusercontent.com/14851080/109227347-098c4a00-7775-11eb-9854-6ed4bea6d6f6.png)

#### deploy.yml
![image](https://user-images.githubusercontent.com/14851080/109227353-0b560d80-7775-11eb-8971-79a4e7f6482b.png)

#### deploy_docker.yml
![image](https://user-images.githubusercontent.com/14851080/109227360-0d1fd100-7775-11eb-862c-e627231eb3b4.png)

**Closed** 2021-03-02 15:44 UTC
Labels: bug

**Comment by thadeu** [comment] 2021-03-24 15:59
I solved problem by renaming file to `deployer.yml ` 

Thanks for help!

**Comment by joshriverscambia2019** [comment] 2021-04-06 20:16
@evidolob with the fixed version of yaml-language-server installed, this issue is not resolved. Files named `deploy.yml` still get the incorrect schema match.

**Comment by evidolob** [comment] 2021-04-07 06:32
Then we need to get https://github.com/redhat-developer/yaml-language-server/pull/427 merged to fix all issues with file match

**Comment by joshmanders** [comment] 2021-05-09 19:28
Any luck on this? I just ran into it creating a github workflow called `deploy.yaml`

**Comment by czmola** [comment] 2021-05-21 20:19
Will there be a release anytime soon?  I'm seeing the issue in v0.19.2  in a fresh vscode install.  Or is there an easy way to patch this in place?

**Comment by fastlorenzo** [comment] 2021-05-22 16:00
@czmola I've used the following work-around: add the following line on top of the yaml file that fails (usually one with `deploy` in the name, in my case `deploy.yml`):
```yaml
# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json
```

That should do the trick until it's fixed 😎

**Comment by czmola** [comment] 2021-05-24 13:47
or the `ansible-role-2.9.json` schema.  if it is a tasklist in a role.

**Comment by piotr-cz** [comment] 2021-07-13 11:53
@fastlorenzo 
This doesn't work for me, I'm getting another error:

```
Unable to load schema from 'd:\xxx\ansible\playbooks\https:\json.schemastore.org\ansible-playbook.json': .
```

**Comment by bermann** [comment] 2021-07-21 00:45
Any news on this I'm experiencing the same issue

**Comment by evidolob** [comment] 2021-07-22 07:01
@bermann Are you using latest version if vscode-yaml?
I cannot reproduce this on my side.

**Comment by bobba76** [comment] 2021-08-03 11:44
I had the same issue but with another schema. 
For me,` hammerkit.json` was auto chosen when creating my `build.yml`

The issue was solved by adding this at the top:

`# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#`

This was the schema that my other yaml file were using.

**Comment by cawoodm** [comment] 2021-08-06 09:46
I'm having the same problem with a file called `build.yaml`. Renaming to `build2.yaml` solves it.

VSCode: 1.58.2
Azure PIpelines Extension: v1.188.1

**Comment by MostefaKamalLala** [comment] 2021-08-10 13:56
For those who don't know how to set the schema settings with:

```JSON
"yaml.schemas": {
  "https://json.schemastore.org/github-workflow": "/.github/workflows/**/*.yml"
}
```

Simply press Ctrl+, in visual code > Extentions > Yaml > Edit in settings.json right after Yaml: completion

**Comment by toshihr** [comment] 2021-09-29 08:12
done

**Comment by lazarillo** [comment] 2022-03-07 17:07
> For those who don't know how to set the schema settings with:
> 
> ```json
> "yaml.schemas": {
>   "https://json.schemastore.org/github-workflow": "/.github/workflows/**/*.yml"
> }
> ```
> 
> Simply press Ctrl+, in visual code > Extentions > Yaml > Edit in settings.json right after Yaml: completion

This seems like exactly what I should need, since the proper schema was not being found.  But I tried it and it did not help. 
 In the screenshot below, I have hovered over a variable in the `env` section.  It _should_ expect a list of any key-value pairs:

![VS Code GitHub Actions Syntax Highlighting Issue](https://user-images.githubusercontent.com/636798/157081459-5a79e569-b94d-4908-9719-50760879dbab.png)

I then double checked [json.schemastore.org/github-workflow](https://json.schemastore.org/github-workflow) and it _says_ that it should work, but it still doesn't.  The relevant snippet:

```json
    "env": {
      "$comment": "https://docs.github.com/en/actions/learn-github-actions/environment-variables",
      "description": "To set custom environment variables, you need to specify the variables in the workflow file. You can define environment variables for a step, job, or entire workflow using the jobs.<job_id>.steps[*].env, jobs.<job_id>.env, and env keywords. For more information, see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsenv",
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": {
            "oneOf": [
              {
                "type": "string"
              },
              {
                "type": "number"
              },
              {
                "type": "boolean"
              }
            ]
          },
          "minProperties": 1
        },
        {
          "$ref": "#/definitions/expressionSyntax",
          "$comment": "https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson",
          "pattern": "^\\$\\{\\{\\s*fromJSON\\(.*\\)\\s*\\}\\}$"
        }
      ]
    },
```

I'm not sure what I'm doing wrong.  Is no one else having this syntax highlighting problem?

For now, I have just turned it off via:

```json
    "files.associations": {
        "/.github/workflows/**/*.yml": "plaintext"
    },
```

in my `settings.json` file.

**Comment by douglaswth** [comment] 2022-03-07 23:38
@lazarillo it looks like the latest version has introduced some issues with how it interprets the GitHub Workflow schema: #691.

**Comment by Wiiki0807** [comment] 2022-04-24 23:43
> I had the same issue but with another schema. For me,` hammerkit.json` was auto chosen when creating my `build.yml`
> 
> The issue was solved by adding this at the top:
> 
> `# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#`
> 
> This was the schema that my other yaml file were using.

This work for me, thanks for tip. @bobba76

**Comment by hdodov** [comment] 2022-06-14 12:36
I also experience strange behavior on Windows with VS Code 1.67.2 and [redhat.vscode-yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) 1.8.0.

A file `site/blueprints/site.yml` for some reason gets validated with the Ansible Playbook schema, turning everything red. I checked all settings (folder, workspace, user) and I have nothing set. Restarting VS Code doesn't help either. The only solution seems to be `"yaml.validate": false`...
