### ISSUE TITLE
enum incorrectly matches partial string

### ISSUE THREAD

**Issue by erik-carlson** [redhat-developer/vscode-yaml#808] opened 2022-08-11 17:08 UTC
## Describe the bug
when using enum on a string, partial strings of the enum values are incorrectly marked as valid

schema:
```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "foo": {
      "enum": ["bar"]
    }
  }
}
```

invalid input:
```
foo: b
```

valid input:
```
foo: bar
```

## Expected Behavior
An issue should be identified as the value does not match any of the valid items in enum

## Current Behavior
no issue is identified with the invalid input above

## Steps to Reproduce
1. validate the invalid input above with the schema

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by msivasubramaniaan** [comment] 2022-08-29 12:22
duplicate of this [issue](https://github.com/redhat-developer/vscode-yaml/issues/803)

**Closed by msivasubramaniaan** 2022-08-29 12:22 UTC
Labels: duplicate
