### ISSUE TITLE
Auto completion doesn't work on empty YAML file

### ISSUE THREAD

**Issue by ppatierno** [redhat-developer/vscode-yaml#148] opened 2018-12-31 14:10 UTC
I have the extension installed but with the following behavior ...
If I create an empty YAML file and try to type something then CTRL + SPACE for suggestions I got "no suggestion" so no auto completion.

![no_suggestions](https://user-images.githubusercontent.com/5842311/50561751-05d41880-0d0e-11e9-918f-ea1df3107468.png)

If with the empty file I just press CTRL + SPACE I got suggestion for creating Kubernetes resources ...

![kube_suggestions](https://user-images.githubusercontent.com/5842311/50561769-1edcc980-0d0e-11e9-9a9f-630780f859ac.png)

Only starting from one of this resources then the auto completion starts to work properly ...

![kube_suggestions_2](https://user-images.githubusercontent.com/5842311/50561776-30be6c80-0d0e-11e9-98a8-82a08d6fb173.png)

What's the problem about that?

**Comment by JPinkney** [comment] 2018-12-31 14:30
Duplicate of https://github.com/redhat-developer/yaml-language-server/issues/51 I believe

**Comment by ppatierno** [comment] 2018-12-31 14:32
It could be but If I write a valid first line and then I try to write something else on the second line, I got no suggestions as well.

**Comment by JPinkney** [comment] 2018-12-31 14:46
Are you using the kubernetes schema directly or are you using the kubernetes extension by Microsoft? For the kubernetes schema it should work fine
<img width="669" alt="screen shot 2018-12-31 at 9 39 18 am" src="https://user-images.githubusercontent.com/8839537/50562193-f4741780-0cdf-11e9-8d27-cffb9ccc794d.png">

However, the kubernetes schema currently doesn't support apiVersion: apps/v1 (its in the process of getting fixed) so that might be that might be an issue with the sample posted above. 

If you're using the kubernetes extension by Microsoft I can really only think of one thing. They use a custom schema that they put into the language server so my suspicion is that the schema they're inserting isn't fully correct but I'm going to take a look to see if that's the case

**Comment by ppatierno** [comment] 2018-12-31 14:50
yeah I have the kubernetes extension by Microsoft installed as well. Should I remove that extension for having this one working?

**Comment by JPinkney** [comment] 2018-12-31 15:03
You can but because the kubernetes schema currently doesn't support apps/v1 (the PR out just needs to be merged and then it can be fixed here). It will probably show an error underlying that but everything else should work

**Comment by ppatierno** [comment] 2018-12-31 15:05
but as far as I understood, even when the PR will be merged, these two extensions are not compatible? I cannot use the Kubernetes extension from MS for handling the Kube clusters and then this extension for the YAML syntax?

**Comment by JPinkney** [comment] 2018-12-31 15:15
When the PR is merged the Microsoft people would have to update the schema in their repository. The kubernetes extension is using this extension for everything yaml but they have a custom resolver that feeds the schema into this extension. If they're using the old schema when it resolves then they're feeding in a schema that wouldn't have the correct autocompletion etc. I believe that if you set up the schema via yaml.schemas setting it should work fine regardless of whether or not the Microsoft people have updated their schema!

**Comment by shashanksdixit** [comment] 2019-10-17 10:05
I have installed this extn today. Auto completion still does not work.

**Comment by JPinkney** [comment] 2020-02-19 22:54
I believe this can be closed now as everything should have been fixed. If it's not let me know.

**Closed by JPinkney** 2020-02-19 22:54 UTC

**Comment by satyamsareen** [comment] 2021-05-08 14:19
Restart your machine and it shall work.
