### ISSUE TITLE
Extension is stealing focus

### ISSUE THREAD

**Issue by morremeyer** [redhat-developer/vscode-yaml#359] opened 2020-08-27 09:14 UTC
Hey everyone,

when the YAML file has errors, e.g.

```
[Error - 11:10:00 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'lineComments' of undefined
  Code: -32603 
```

the extension (in the latest version `0.10.0` logs that to the „OUTPUT“ tab and steals the focus so that the Output tab is in focus.

This is really annoying as I want e.g. my terminal to stay open. Can you look into deactivating this behavior?

Thanks?

**Comment by JPinkney** [comment] 2020-08-27 11:55
Duplicate of https://github.com/redhat-developer/vscode-yaml/issues/358. Any error automatically opens the panel. Nothing we can do. Theres a fix in the works.

**Comment by powerfulsheron** [comment] 2021-02-04 10:15
@JPinkney there is something you can do see https://github.com/microsoft/vscode/issues/31474#issuecomment-319032829

**Comment by ssbarnea** [comment] 2021-02-09 12:50
I wonder if that is what drove me insane when I try to use create folder/file and the input field was magically loosing focus before being able to type.

**Comment by evidolob** [comment] 2021-02-09 13:04
@powerfulsheron Not exactly, we use https://github.com/microsoft/vscode-languageserver-node/tree/master/client to interact with Language Server. That client use output channel to log all errors received from language server. 

I think we can try to handle that, need to experiment with it.

**Closed** 2021-02-10 07:39 UTC
