### ISSUE TITLE
Unable to load schema from ... self signed certificate in certificate chain.

### ISSUE THREAD

**Issue by mrdulin** [redhat-developer/vscode-yaml#384] opened 2020-10-29 07:05 UTC
## Summary

`cron.yaml`:
```yaml
apiVersion: batch/v1 
```

>  Unable to load schema from 'https://raw.githubusercontent.com/instrumenta/kubernetes-json-schema/master/v1.17.0-standalone-strict/all.json': self signed certificate in certificate chain.(768)

## Relevant information

Is there any way to bypass this certificate verify? I can access the above link from my browser.

Related issue: https://github.com/redhat-developer/vscode-yaml/issues/107

**Comment by JPinkney** [comment] 2020-11-16 20:43
I think this issue is actually a duplicate of https://github.com/redhat-developer/vscode-yaml/issues/107 since it seems to be the same cause. If you have any instructions on how to reproduce it please post on the other issue and I'll try to take a look when I can

**Closed by JPinkney** 2020-11-16 20:43 UTC
