### ISSUE TITLE
Provide a way to refresh cached schemas

### ISSUE THREAD

**Issue by brettcannon** [redhat-developer/vscode-yaml#497] opened 2021-04-28 18:02 UTC
### Is your enhancement related to a problem? Please describe.
GitHub Actions recently updated their format for their workflow files (https://json.schemastore.org/github-workflow), but the extension keeps saying the new additions are invalid even though the schema has been updated (this is in regards to the new `permissions` field).

### Describe the solution you would like
A command to forcibly refresh schemas.

### Describe alternatives you have considered
I'm not sure how often schemas are being automatically refreshed, but unless it's a HEAD HTTP call per launch it seems to not necessarily be frequent enough.

**Comment by ssbarnea** [comment] 2021-04-28 22:02
I suspect the problem is not in yaml extension because I use it to point to github raw files and they get updated almost instantly. At least github does a really good job on respecting http specification.

Still, what jsonschema.org does with serving files is bit fishy, I personally got recurring problems with them including expired SSL certificates (every 3 months it has few hours of downtine for sure).

Or maybe what is cached incorrectly is the schema index/mapping, not the schemas themselves.

**Comment by ssbarnea** [comment] 2022-02-04 11:41
@brettcannon Are you sure that reloading code does not refresh the schemas? For me that worked fine so far as I had numerous contributions to those schemas, including some to the workflow one.

If reloading code is enough (`Reload Window`), i would suggest just closing this.

Keep in mind that schemasstore uses a CDN, so I would not rule out some caching issues on their side too.

**Closed** 2022-02-04 18:54 UTC

**Comment by beanaroo** [comment] 2022-07-05 08:28
@ssbarnea I've noticed that even when working with local schemas (`node_modules/@my/internal/schema.json`), there is no change in validation when it is updated.

Your suggestion above to `Reload Window` does indeed work but requires us to remind everyone to reload their code any time there is an update to the schema.

I can tell that when using Jetbrains, the refresh is instant.

I'm not familiar with VSCode extensions, but would something like a [Filesystem Watcher](https://github.com/redhat-developer/vscode-yaml/issues/190) on locally referenced schemas be useful in this case?

**Comment by ssbarnea** [comment] 2022-07-05 10:37
I am not sure in which case it works or not because I seen it being able to refresh without having to reload window. It might be a bug.
