### ISSUE TITLE
pasting multiple full lines adds additional indentation on first pasted line, causing bad indentation error

### ISSUE THREAD

**Issue by danipindado** [redhat-developer/vscode-yaml#74] opened 2018-03-19 08:48 UTC
hi, 
since a week or so i have observed an annoying issue when copying and pasting whole lines. 
the lines are properly pasted, but afterwards the first copied line is indented. 
this causes a bad indentation error. 
i know is coming from the yaml extension, because if i disable it, it works just fine. 

the workaround is to paste the lines of code, and then, press once ctrl-z ( undo). if I do this, the extra indentation is removed. 

any ideas what might be causing the problem?

I am running latest vscode on w7-64bits.

thank you in advance

**Comment by JPinkney** [comment] 2018-03-19 17:24
Is there anyway you can show a gif of this happening? I cannot reproduce. There isn't any functionality that does auto indents of any sort so I'm not sure where it is coming from.

@gorkem Are you able to reproduce?

**Comment by danipindado** [comment] 2018-03-19 18:14
hi, 
yes sorry. today in the morning i was not able of uploading a gif. for some reason now is working. 
i have the same issue in two different computers.

![2018-03-19_19h06_46](https://user-images.githubusercontent.com/22555491/37613957-ab3fa164-2ba9-11e8-8cb0-e48911ee0eaf.gif)

**Comment by JPinkney** [comment] 2018-03-19 18:24
I can reproduce now. Weirdest bug I've seen in a while because the extension isn't doing anything directly that should change the paste. I'll look into it more to see why its happening

**Comment by JPinkney** [comment] 2018-04-04 03:11
I found out why this is happening. VSCode introduced an auto indent feature that messes with the default indentation settings. The extension will now have to contribute indentation rules: https://code.visualstudio.com/updates/v1_14#_auto-indent-on-type-move-lines-and-paste. I'm looking into how I can fix this.

**Comment by JPinkney** [comment] 2018-04-04 03:53
Fixed and will be in our newest version hopefully released monday!

**Closed by JPinkney** 2018-04-04 03:53 UTC
Labels: bug
