### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by pratiksanyaja1998** [redhat-developer/vscode-yaml#590] opened 2021-09-11 09:26 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-yaml`
- Extension Version: `0.22.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.60.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8885,
		"activateCallTime": 2,
		"activateResolvedTime": 50,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "atlassian.atlascode",
				"_lower": "atlassian.atlascode"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by gorkem** [comment] 2022-03-06 02:53
I am not able to reproduce with the later versions, please provide better instructions for us to be able to reproduce. Closing for now.

**Closed by gorkem** 2022-03-06 02:53 UTC
